vocab_path: /home/jarvis/jw_ws/Verification_ws/SwitchLoop/DBoW2/Vocabulary/ORBvoc.txt
image_path: /mnt/jw_ssd/jw_ws/Verification_ws/GV-Bench/dataset/images
pairs_path: /home/jarvis/jw_ws/Verification_ws/GV-Bench/dataset/gt/hotel.txt
scores_path: /home/jarvis/jw_ws/vpr_ws/SimpleLoopDetector/output/hotel_scores.txt